#+title: Hippie Completing Read
#+subtitle: toward a unified Emacs completing UI

I use ~completing-read~ in Emacs.  I even use it in lieu of popular completion
packages like =company= and such, for ~completion-in-region~.  The one final thorn
in my side was using =hippie-expand=, which completes some things better, or at
least … /different-er/, than regular ~completion-in-region~ commands.  So I went
searching for how to combine both things.

Deep in the back waters of EmacsWiki, I found it: code for an [[https://www.emacswiki.org/emacs/HippieExpand#h5o-11][=ido= interface
to =completing-read=]].  It was easy to adapt to ~completing-read~ code, so I did,
and here's the package.

* Install

You should honestly know how to install packages in Emacs, but you can use
=straight.el=:

#+begin_src emacs-lisp
  (straight-use-package '(hippie-completing-read))
#+end_src

and you should be good to go.

* Using

=hippie-completing-read= exposes one function, aptly called
~hippie-completing-read~.  I bind it thusly:

 #+begin_src emacs-lisp
   (global-set-key (kbd "M-/") #'hippie-completing-read)
 #+end_src

* Contributing

IDK, open an issue, or whatever.

* License

=hippie-completing-read= and associated files are all licensed under the Good
Choices License, the entire text of which is quoted below.

#+begin_example
  License:

  Everyone is permitted to do whatever with this software, without
  limitation.  This software comes without any warranty whatsoever,
  but with two pieces of advice:

  - Be kind to yourself.

  - Make good choices.
#+end_example
